-- PROFO Aankoopbeheer - optionele statusgeschiedenis.
-- Voer dit bestand uit in de Supabase SQL Editor wanneer je statuswijzigingen
-- apart wil kunnen auditeren.
--
-- De applicatie blijft werken zonder deze tabel. Met deze tabel wordt bij elke
-- statuswijziging ook vastgelegd wie de wijziging deed en wanneer.

create table if not exists public.aankoop_bestelling_statuslog (
  id bigint generated by default as identity primary key,
  bestelling_id bigint not null references public.aankoop_bestellingen(id) on delete cascade,
  status text not null,
  actor_naam text,
  actor_email text,
  created_at timestamptz not null default now()
);

create index if not exists aankoop_bestelling_statuslog_bestelling_idx
  on public.aankoop_bestelling_statuslog (bestelling_id, created_at desc);

alter table public.aankoop_bestelling_statuslog enable row level security;

drop policy if exists aankoop_statuslog_insert_ingelogde_gebruiker
  on public.aankoop_bestelling_statuslog;

create policy aankoop_statuslog_insert_ingelogde_gebruiker
  on public.aankoop_bestelling_statuslog
  for insert
  to authenticated
  with check (auth.uid() is not null);

drop policy if exists aankoop_statuslog_select_beheerder
  on public.aankoop_bestelling_statuslog;

create policy aankoop_statuslog_select_beheerder
  on public.aankoop_bestelling_statuslog
  for select
  to authenticated
  using (
    lower(auth.jwt() ->> 'email') in (
      'jorn.neeus@profo.be',
      'kathleen.nerinckx@profo.be'
    )
  );
