-- PROFO Aankoopbeheer
-- Uitvoeren in dezelfde Supabase-projectomgeving als PROFO Voertuigenbeheer.
-- De bestaande tabellen public.gebruikers en public.locaties blijven de bron voor medewerkers en locaties.
-- Belangrijk in Supabase SQL Editor: selecteer en voer dit bestand volledig uit.
-- Een losse kolomregel, bijvoorbeeld "eenheidsprijs_excl_btw numeric(12, 2) not null,"
-- is geen zelfstandige SQL-opdracht en geeft een syntax error.
-- Dit volledige bestand verwacht dat public.gebruikers en public.locaties al bestaan.
-- Als dat niet zo is, gebruik de stapbestanden: stap 1 legt de aankoop-tabellen zonder foreign keys aan.

create table if not exists public.aankoop_producten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  naam text not null,
  categorie text not null default 'Algemeen',
  leverancier text,
  leverancier_url text,
  omschrijving text,
  eenheid text not null default 'stuk',
  prijs_excl_btw numeric(12, 2) not null default 0,
  btw_percentage numeric(5, 2) not null default 21,
  minimum_bestelhoeveelheid integer not null default 1 check (minimum_bestelhoeveelheid > 0),
  image_url text,
  actief boolean not null default true,
  sort_order integer not null default 100
);

create table if not exists public.aankoop_bestellingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  locatie_id bigint,
  locatie_naam text not null,
  besteller_id bigint,
  besteller_naam text not null,
  besteller_email text not null,
  aangemaakt_door_id bigint,
  aangemaakt_door_email text,
  status text not null default 'Nieuw',
  opmerkingen text,
  totaal_excl_btw numeric(12, 2) not null default 0,
  totaal_btw numeric(12, 2) not null default 0,
  totaal_incl_btw numeric(12, 2) not null default 0,
  mail_status text not null default 'Nog niet verzonden',
  mail_verzonden_op timestamptz
);

create table if not exists public.aankoop_bestelregels (
  id bigint generated by default as identity primary key,
  bestelling_id bigint not null references public.aankoop_bestellingen(id) on delete cascade,
  product_id bigint references public.aankoop_producten(id) on delete set null,
  product_naam text not null,
  product_omschrijving text,
  aantal integer not null check (aantal > 0),
  eenheid text,
  eenheidsprijs_excl_btw numeric(12, 2) not null,
  btw_percentage numeric(5, 2) not null default 21,
  lijn_totaal_excl_btw numeric(12, 2) not null,
  lijn_totaal_btw numeric(12, 2) not null,
  lijn_totaal_incl_btw numeric(12, 2) not null
);

create index if not exists aankoop_producten_actief_idx on public.aankoop_producten (actief, categorie, naam);
create unique index if not exists aankoop_producten_naam_unique_idx on public.aankoop_producten (lower(naam));
create index if not exists aankoop_bestellingen_besteller_idx on public.aankoop_bestellingen (besteller_id, created_at desc);
create index if not exists aankoop_bestellingen_aangemaakt_door_idx on public.aankoop_bestellingen (aangemaakt_door_id, created_at desc);
create index if not exists aankoop_bestelregels_bestelling_idx on public.aankoop_bestelregels (bestelling_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_aankoop_producten_updated_at on public.aankoop_producten;
create trigger set_aankoop_producten_updated_at
before update on public.aankoop_producten
for each row execute function public.set_updated_at();

drop trigger if exists set_aankoop_bestellingen_updated_at on public.aankoop_bestellingen;
create trigger set_aankoop_bestellingen_updated_at
before update on public.aankoop_bestellingen
for each row execute function public.set_updated_at();

alter table public.aankoop_producten enable row level security;
alter table public.aankoop_bestellingen enable row level security;
alter table public.aankoop_bestelregels enable row level security;

drop policy if exists aankoop_producten_authenticated_select on public.aankoop_producten;
drop policy if exists aankoop_producten_beheerder_all on public.aankoop_producten;

create policy aankoop_producten_authenticated_select
  on public.aankoop_producten
  for select
  to authenticated
  using (actief = true or public.current_gebruiker_is_beheerder());

create policy aankoop_producten_beheerder_all
  on public.aankoop_producten
  for all
  to authenticated
  using (public.current_gebruiker_is_beheerder())
  with check (public.current_gebruiker_is_beheerder());

drop policy if exists aankoop_bestellingen_select_betrokken_of_beheerder on public.aankoop_bestellingen;
drop policy if exists aankoop_bestellingen_insert_eigen_sessie on public.aankoop_bestellingen;
drop policy if exists aankoop_bestellingen_update_beheerder on public.aankoop_bestellingen;

create policy aankoop_bestellingen_select_betrokken_of_beheerder
  on public.aankoop_bestellingen
  for select
  to authenticated
  using (
    public.current_gebruiker_is_beheerder()
    or besteller_id = public.current_gebruiker_id()
    or aangemaakt_door_id = public.current_gebruiker_id()
  );

create policy aankoop_bestellingen_insert_eigen_sessie
  on public.aankoop_bestellingen
  for insert
  to authenticated
  with check (
    aangemaakt_door_id = public.current_gebruiker_id()
  );

create policy aankoop_bestellingen_update_beheerder
  on public.aankoop_bestellingen
  for update
  to authenticated
  using (public.current_gebruiker_is_beheerder())
  with check (public.current_gebruiker_is_beheerder());

drop policy if exists aankoop_bestelregels_select_betrokken_of_beheerder on public.aankoop_bestelregels;
drop policy if exists aankoop_bestelregels_insert_bij_eigen_bestelling on public.aankoop_bestelregels;
drop policy if exists aankoop_bestelregels_update_beheerder on public.aankoop_bestelregels;

create policy aankoop_bestelregels_select_betrokken_of_beheerder
  on public.aankoop_bestelregels
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.aankoop_bestellingen bestelling
      where bestelling.id = aankoop_bestelregels.bestelling_id
        and (
          public.current_gebruiker_is_beheerder()
          or bestelling.besteller_id = public.current_gebruiker_id()
          or bestelling.aangemaakt_door_id = public.current_gebruiker_id()
        )
    )
  );

create policy aankoop_bestelregels_insert_bij_eigen_bestelling
  on public.aankoop_bestelregels
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.aankoop_bestellingen bestelling
      where bestelling.id = aankoop_bestelregels.bestelling_id
        and bestelling.aangemaakt_door_id = public.current_gebruiker_id()
    )
  );

create policy aankoop_bestelregels_update_beheerder
  on public.aankoop_bestelregels
  for update
  to authenticated
  using (public.current_gebruiker_is_beheerder())
  with check (public.current_gebruiker_is_beheerder());

do $$
begin
  if to_regprocedure('public.audit_row_change()') is not null then
    drop trigger if exists audit_aankoop_producten_changes on public.aankoop_producten;
    create trigger audit_aankoop_producten_changes
    after insert or update or delete on public.aankoop_producten
    for each row execute function public.audit_row_change();

    drop trigger if exists audit_aankoop_bestellingen_changes on public.aankoop_bestellingen;
    create trigger audit_aankoop_bestellingen_changes
    after insert or update or delete on public.aankoop_bestellingen
    for each row execute function public.audit_row_change();

    drop trigger if exists audit_aankoop_bestelregels_changes on public.aankoop_bestelregels;
    create trigger audit_aankoop_bestelregels_changes
    after insert or update or delete on public.aankoop_bestelregels
    for each row execute function public.audit_row_change();
  end if;
end $$;

insert into public.aankoop_producten (
  naam,
  categorie,
  leverancier,
  leverancier_url,
  omschrijving,
  eenheid,
  prijs_excl_btw,
  btw_percentage,
  minimum_bestelhoeveelheid,
  image_url,
  sort_order
)
values (
  'Gevouwen handdoeken 2-laags - geschikt voor Tork H2 dispenser',
  'Sanitair en hygiene',
  '123schoon.nl',
  'https://www.123schoon.nl/',
  'Papieren handdoekjes voor professioneel sanitair gebruik. Startproduct op basis van het aangeleverde voorbeeld; prijs blijft door beheer te controleren bij de leverancier.',
  'doos van 20 pakken',
  35.12,
  21,
  1,
  '/assets/gevouwen-handdoeken-voorbeeld.png',
  10
)
on conflict do nothing;

comment on table public.aankoop_producten is 'Catalogus voor het interne PROFO-bestelportaal.';
comment on table public.aankoop_bestellingen is 'Bestellingen door PROFO-medewerkers voor locaties.';
comment on table public.aankoop_bestelregels is 'Productregels gekoppeld aan interne PROFO-bestellingen.';
