-- PROFO Aankoopbeheer - stap 1
-- Voer dit volledige bestand uit in Supabase SQL Editor.
-- Selecteer alles met Ctrl+A voordat je op Run klikt.
-- Deze stap legt alleen de aankoop-tabellen aan.
-- De koppeling met bestaande PROFO-tabellen gebeurt bewust pas later,
-- zodat deze stap niet blokkeert wanneer je per ongeluk in een Supabase-project zonder public.locaties of public.gebruikers zit.

create table if not exists public.aankoop_producten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  naam text not null,
  categorie text not null default 'Algemeen',
  leverancier text,
  leverancier_url text,
  omschrijving text,
  eenheid text not null default 'stuk',
  prijs_excl_btw numeric(12, 2) not null default 0,
  btw_percentage numeric(5, 2) not null default 21,
  minimum_bestelhoeveelheid integer not null default 1 check (minimum_bestelhoeveelheid > 0),
  image_url text,
  actief boolean not null default true,
  sort_order integer not null default 100
);

create table if not exists public.aankoop_bestellingen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  locatie_id bigint,
  locatie_naam text not null,
  besteller_id bigint,
  besteller_naam text not null,
  besteller_email text not null,
  aangemaakt_door_id bigint,
  aangemaakt_door_email text,
  status text not null default 'Nieuw',
  opmerkingen text,
  totaal_excl_btw numeric(12, 2) not null default 0,
  totaal_btw numeric(12, 2) not null default 0,
  totaal_incl_btw numeric(12, 2) not null default 0,
  mail_status text not null default 'Nog niet verzonden',
  mail_verzonden_op timestamptz
);

create table if not exists public.aankoop_bestelregels (
  id bigint generated by default as identity primary key,
  bestelling_id bigint not null references public.aankoop_bestellingen(id) on delete cascade,
  product_id bigint references public.aankoop_producten(id) on delete set null,
  product_naam text not null,
  product_omschrijving text,
  aantal integer not null check (aantal > 0),
  eenheid text,
  eenheidsprijs_excl_btw numeric(12, 2) not null,
  btw_percentage numeric(5, 2) not null default 21,
  lijn_totaal_excl_btw numeric(12, 2) not null,
  lijn_totaal_btw numeric(12, 2) not null,
  lijn_totaal_incl_btw numeric(12, 2) not null
);
