-- PROFO Aankoopbeheer - stap 0 basisgegevens
-- Voer dit volledige bestand eerst uit in het aparte Supabase-project voor Aankoopbeheer.
-- Dit project krijgt eigen tabellen voor dezelfde basisgegevens als Voertuigenbeheer:
-- public.gebruikers en public.locaties.

create table if not exists public.gebruikers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  auth_user_id uuid references auth.users(id) on delete set null,
  naam text not null,
  email text not null unique,
  functie text,
  rol text not null default 'Gebruiker',
  actief boolean not null default true
);

create unique index if not exists gebruikers_email_unique_idx
  on public.gebruikers (lower(email));

create unique index if not exists gebruikers_email_exact_unique_idx
  on public.gebruikers (email);

create unique index if not exists gebruikers_auth_user_id_unique_idx
  on public.gebruikers (auth_user_id)
  where auth_user_id is not null;

create table if not exists public.locaties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  naam text not null,
  adres text,
  actief boolean not null default true,
  sort_order integer not null default 100
);

create unique index if not exists locaties_naam_unique_idx
  on public.locaties (lower(naam));

insert into public.gebruikers (naam, email, functie, rol, actief)
values ('Jorn Neeus', 'jorn.neeus@profo.be', 'Preventieadviseur / DPO', 'Beheerder', true)
on conflict (email) do update
set
  naam = excluded.naam,
  functie = excluded.functie,
  rol = excluded.rol,
  actief = excluded.actief;
