create table if not exists public.aankoop_printers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  locatie_id text not null,
  locatie_naam text not null,
  naam text not null,
  merk text,
  model text,
  inventaris_id text,
  inventaris_url text,
  actief boolean not null default true,
  sort_order integer not null default 100
);

alter table public.aankoop_printers
  add column if not exists inventaris_id text;

alter table public.aankoop_printers
  add column if not exists inventaris_url text;

create table if not exists public.aankoop_printer_cartridges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  printer_id bigint not null references public.aankoop_printers(id) on delete cascade,
  kleur text not null check (kleur in ('BK', 'C', 'M', 'Y', 'SET')),
  naam text not null,
  artikelnummer text,
  leverancier text not null default '123inkt.nl',
  leverancier_url text,
  prijs_incl_btw numeric(12, 2) not null default 0,
  btw_percentage numeric(5, 2) not null default 21,
  eenheid text not null default 'stuk',
  actief boolean not null default true,
  sort_order integer not null default 100
);

create index if not exists aankoop_printers_locatie_idx
  on public.aankoop_printers (locatie_id, actief, sort_order, naam);

create unique index if not exists aankoop_printers_inventaris_id_unique_idx
  on public.aankoop_printers (inventaris_id)
  where inventaris_id is not null and inventaris_id <> '';

create index if not exists aankoop_printer_cartridges_printer_idx
  on public.aankoop_printer_cartridges (printer_id, actief, kleur, sort_order);

comment on table public.aankoop_printers is 'Printers per PROFO-locatie voor interne inkt- en tonerbestellingen.';
comment on table public.aankoop_printer_cartridges is 'Cartridges en toners per printer, gekoppeld aan kleur en leverancier.';
